import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import TopBar from "../../../components/Navigation/TopBar";
import PageTitle from "../../../components/PageTitle";
import DefaultSEO from "../../../components/SEO";
import { getItem } from "../../../helpers/localStorage";

const Staff: NextPage = () => {
  const router = useRouter();

  const checkToken = async () => {
    const token = await getItem("token");
    if (!token || token === undefined || token === "undefined")
      router.push("/auth/login");
  };
  useEffect(() => {
    checkToken();
  });
  return (
    <div className="bg-[#E8EDF2] h-full min-h-screen dark:bg-[#0F0F12]">
      <Head>
        <title>Check Staff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <DefaultSEO />
      </Head>
      <TopBar />
      <div className="w-[100%] block relative h-full min-h-[89vh] p-[3em] px-[10%]">
        <PageTitle
          title="Staff"
          addBreadcrumb
          linksBreadcrumb={[
            {
              Name: "Home",
              Url: "/",
              icon: "/svg/home-2.svg",
            },
            {
              Name: "Staff",
              Url: "/dashboard/staff",
            },
          ]}
        />
      </div>
    </div>
  );
};

export default Staff;
