import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import router from "next/router";
import react, { useContext } from "react";
import Footer from "../components/Footer";
import TopBar from "../components/Navigation/TopBar";
import { UserContext } from "../contexts/userContext/UserContext";
import { getItem } from "../helpers/localStorage";
import { loginWithToken } from "../helpers/serverRequests/authUser";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="bg-[#E8EDF2] h-full min-h-screen dark:bg-[#0F0F12]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />

      <Footer />
    </div>
  );
};

export default Home;